server:
  port: 8182
spring:
  application:
    name: resource-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
resilience4j:
  circuitbreaker:
    instances:
      resource-service:
          registerHealthIndicator: true
          eventConsumerBufferSize: 10
          automaticTransitionFromOpenToHalfOpenEnabled: true
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          waitDurationInOpenState: 5s
          slidingWindowType: COUNT_BASED
