server:
  port: 8662
spring:
  application:
    name: gateway-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    resource-service:
      path: /resource/**
      serviceId: resource-service
      stripPrefix: true
    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
#resource-service:
#  ribbon:
#    listOfServers: localhost:8182
#user-service:
#  ribbon:
#    listOfServers: localhost:8183